### ISSUE TITLE
"Crash"

### ISSUE THREAD

**Issue by lukaro707** [WistfulHopes/GGSTReplayTakeover#1]
Game throws an error when launching. I can still play the game normally, but replay takeover doesn't work, and I get a popup saying "Fatal Error: Crashdump written to (My GGST install location)". I'll attach the crashdump file. 
[crash_2024_01_28_12_10_17.dmp](https://github.com/WistfulHopes/GGSTReplayTakeover/files/14075993/crash_2024_01_28_12_10_17.dmp)

**Comment by WistfulHopes** [comment]
yeah i just found out this is an issue normally, you can use [Steamless](https://github.com/atom0s/Steamless) on the game to bypass this but i'll talk to the team behind ue4ss for fixes

**Comment by lukaro707** [comment]
Tried Steamless. No longer getting the fatal error, but none of replay takeover's functionality works.

**Comment by WistfulHopes** [comment]
huh, that's weird. is there anything in UE4SS.log?

**Comment by lukaro707** [comment]
Here you go. Only thing in here that looks like an error to me is "Failed to load .NET Core Runtime". Is there maybe something .NET related I have to install?
[UE4SS.log](https://github.com/WistfulHopes/GGSTReplayTakeover/files/14076796/UE4SS.log)

**Comment by WistfulHopes** [comment]
ah yeah, that would be why. try installing the [.NET 8 runtime](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)

**Comment by WistfulHopes** [comment]
wait shit, it seems like i'm using a preview version of .net. let me fix that

**Comment by WistfulHopes** [comment]
okay that's taken care of, you should be able to use it by installing the aforementioned runtime

**Comment by lukaro707** [comment]
Ok, it's almost working. I can takeover both players, as well as set and rewind to rewind points. There is a new problem it seems: basically, my buttons are doing the wrong thing. Should I create a new issue for that?

**Comment by lukaro707** [comment]
Ok, gonna close this issue and open a new one for the bindings issue.
